-- ============================================================
-- 안보라 국어 학원 - Supabase 데이터베이스 설정
-- ============================================================
-- 이 SQL을 Supabase 대시보드 > SQL Editor에서 실행하세요.
-- 순서대로 전체를 한 번에 실행하면 됩니다.
-- ============================================================


-- ============ 1단계: 테이블 생성 ============

-- 배너 슬라이더
create table if not exists banners (
  id bigint generated by default as identity primary key,
  title text not null default '',
  title_after text not null default '',
  subtitle text not null default '',
  bg_image text not null default '',
  btn_text text not null default '',
  btn_link text not null default '',
  created_at timestamptz not null default now()
);

-- 강사
create table if not exists instructors (
  id bigint generated by default as identity primary key,
  name text not null default '',
  position text not null default '',
  description text not null default '',
  img text not null default '',
  link text not null default '',
  link_label text not null default '',
  created_at timestamptz not null default now()
);

-- 교육과정
create table if not exists curriculum (
  id bigint generated by default as identity primary key,
  title text not null default '',
  tag text not null default '',
  description text not null default '',
  target text not null default '',
  schedule text not null default '',
  created_at timestamptz not null default now()
);

-- 공지사항
create table if not exists notices (
  id bigint generated by default as identity primary key,
  title text not null default '',
  date text not null default '',
  content text not null default '',
  important boolean not null default false,
  created_at timestamptz not null default now()
);

-- 입학 테스트 절차
create table if not exists test_steps (
  id bigint generated by default as identity primary key,
  title text not null default '',
  description text not null default '',
  created_at timestamptz not null default now()
);

-- 입학 테스트 안내 (단일 행 테이블 - 항상 id=1인 행 하나만 존재)
create table if not exists test_info (
  id bigint primary key default 1,
  schedule text not null default '',
  duration text not null default '',
  areas text not null default '',
  materials text not null default '',
  cost text not null default '',
  phone text not null default '',
  form_url text not null default '',
  constraint test_info_single_row check (id = 1)
);

-- 연락처
create table if not exists contacts (
  id bigint generated by default as identity primary key,
  name text not null default '',
  phone text not null default '',
  link text not null default '',
  link_label text not null default '',
  created_at timestamptz not null default now()
);

-- 캠퍼스 약도
create table if not exists map_branches (
  id bigint generated by default as identity primary key,
  name text not null default '',
  label text not null default '',
  addr text not null default '',
  note text not null default '',
  map_query text not null default '',
  created_at timestamptz not null default now()
);

-- 약도 부가정보 (단일 행 테이블)
create table if not exists map_info (
  id bigint primary key default 1,
  transport text not null default '',
  hours text not null default '',
  constraint map_info_single_row check (id = 1)
);

-- 이용약관
create table if not exists terms (
  id bigint generated by default as identity primary key,
  title text not null default '',
  content text not null default '',
  created_at timestamptz not null default now()
);

-- 개인정보처리방침
create table if not exists privacy (
  id bigint generated by default as identity primary key,
  title text not null default '',
  content text not null default '',
  created_at timestamptz not null default now()
);


-- ============ 2단계: 기본 데이터 삽입 ============

-- 배너
insert into banners (title, title_after, subtitle, bg_image, btn_text, btn_link) values
  ('국어의 힘', '을 키우는 곳', '체계적인 커리큘럼과 최고의 강사진이 함께하는 안보라에서 국어 실력의 차이를 만들어 보세요.', '', '입학 테스트 신청', '#test');

-- 강사
insert into instructors (name, position, description, img, link, link_label) values
  ('김서윤', '대표 강사 · 국어 문학', '서울대학교 국어국문학과 졸업. 15년간 수능 국어 강의 경력. 문학 영역 전문.', '', '', ''),
  ('박준혁', '수석 강사 · 비문학/독서', '고려대학교 국어교육과 졸업. EBS 연계 교재 집필 참여. 비문학 독해 전략 전문.', '', '', ''),
  ('이하은', '전임 강사 · 문법/언어', '연세대학교 국어학 석사. 언어와 매체, 문법 영역 전문. 친절한 개념 설명.', '', '', '');

-- 교육과정
insert into curriculum (title, tag, description, target, schedule) values
  ('수능 국어 기본 완성반', '기초', '국어 전 영역의 기본 개념과 핵심 원리를 체계적으로 학습합니다. 문학, 독서, 언어와 매체의 기초를 다집니다.', '고1 · 고2', '월/수/금 16:00 ~ 18:00'),
  ('수능 국어 실력 도약반', '심화', '기본 개념을 바탕으로 실전 문제 풀이 능력을 키웁니다. 고난도 지문 분석 및 시간 관리 전략을 훈련합니다.', '고2 · 고3', '화/목/토 16:00 ~ 18:30'),
  ('수능 국어 파이널 특강반', '파이널', '수능 직전 실전 모의고사와 취약 영역 집중 보완. 최종 점검 및 시험장 전략을 수립합니다.', '고3 · N수생', '월~토 19:00 ~ 21:30'),
  ('내신 국어 대비반', '내신', '학교별 교과서 분석 및 서술형 평가 대비. 내신 만점을 위한 맞춤 학습 프로그램.', '고1 · 고2', '시험 3주 전 개강');

-- 공지사항
insert into notices (title, date, content, important) values
  ('2026년 봄학기 수강 신청 안내', '2026-02-10', E'안녕하세요, 안보라입니다.\n\n2026년 봄학기 수강 신청이 2월 17일(월)부터 시작됩니다.\n\n■ 신청 기간: 2026.02.17 ~ 2026.02.28\n■ 개강일: 2026.03.03 (월)\n■ 신청 방법: 방문 접수 또는 전화 접수\n\n조기 마감될 수 있으니 서둘러 신청해 주세요.\n감사합니다.', true),
  ('입학 테스트 일정 안내 (3월)', '2026-02-08', E'3월 입학 테스트 일정을 안내드립니다.\n\n■ 일시: 2026.02.22 (토) 오전 10:00\n■ 장소: 학원 3층 대강의실\n■ 소요시간: 약 60분\n■ 준비물: 필기도구\n\n사전 예약 필수이며, 전화로 신청해 주세요.\n감사합니다.', true),
  ('설 연휴 휴원 안내', '2026-02-01', E'설 연휴 기간 동안 학원이 휴원합니다.\n\n■ 휴원 기간: 2026.01.28 (화) ~ 2026.02.02 (일)\n■ 정상 수업: 2026.02.03 (월)부터\n\n즐거운 명절 보내세요!', false),
  ('2025 수능 국어 성적 우수자 발표', '2026-01-20', E'2025학년도 수능 국어 영역에서 우수한 성적을 거둔 학생들을 축하합니다.\n\n■ 1등급 배출: 12명\n■ 2등급 이내: 38명\n\n학생들의 노력에 박수를 보냅니다.\n상세 내용은 학원 게시판을 확인해 주세요.', false),
  ('교재 수령 안내', '2026-01-15', E'봄학기 교재가 입고되었습니다.\n\n수강 신청 완료 학생은 학원 사무실에서 교재를 수령해 주세요.\n\n■ 수령 시간: 평일 14:00 ~ 20:00\n■ 준비물: 수강증\n\n감사합니다.', false);

-- 테스트 절차
insert into test_steps (title, description) values
  ('전화 예약', '학원으로 전화(02-1234-5678)하여 원하는 테스트 일정을 예약합니다.'),
  ('테스트 응시', '예약 일시에 방문하여 국어 전 영역 레벨 테스트(60분)를 응시합니다.'),
  ('결과 상담', '테스트 결과를 바탕으로 담당 강사와 1:1 상담을 진행합니다.'),
  ('반 배정 · 수강 시작', '실력에 맞는 최적의 반에 배정되어 수강을 시작합니다.');

-- 테스트 안내 (단일 행)
insert into test_info (id, schedule, duration, areas, materials, cost, phone, form_url) values
  (1, '매주 토요일 오전 10:00 (사전 예약 필수)', '약 60분', '문학, 독서(비문학), 언어와 매체(문법)', '필기도구, 학생증', '무료', '02-1234-5678', '');

-- 연락처
insert into contacts (name, phone, link, link_label) values
  ('본관', '02-556-8383', '', ''),
  ('카카오톡 상담', '', 'https://pf.kakao.com/', '카카오톡 상담'),
  ('네이버 카페', '', 'https://cafe.naver.com/', '네이버 카페');

-- 캠퍼스
insert into map_branches (name, label, addr, note, map_query) values
  ('아르누보관', '메인', '서울특별시 강남구 도곡로 405, 삼환아르누보 2차 3층', '', '서울 강남구 도곡로 405'),
  ('한티관', '', '서울특별시 강남구 선릉로 318, 동궁상가 2층', '한티역 1번 출구 오른쪽 약 100m, 노브랜드 건물 2층', '서울 강남구 선릉로 318'),
  ('디마크관', '', '서울특별시 강남구 도곡로 408, 디마크빌딩 5층 509호', '한티역 3번 출구 약 110m', '서울 강남구 도곡로 408');

-- 약도 부가정보 (단일 행)
insert into map_info (id, transport, hours) values
  (1, E'지하철: 수인분당선 한티역 1번 · 3번 출구\n버스: 한티역 정류장 하차 (강남06, 4412)', '화~금 15:00 ~ 22:00 / 토~일 10:00 ~ 22:00 / 월요일 정기 휴무');

-- 이용약관
insert into terms (title, content) values
  ('제1조 (목적)', '본 약관은 안보라(이하 "학원")이 운영하는 웹사이트(이하 "사이트")에서 제공하는 서비스의 이용과 관련하여 학원과 이용자 간의 권리·의무 및 기타 필요한 사항을 규정함을 목적으로 합니다.'),
  ('제2조 (용어의 정의)', E'"사이트"란 학원이 교육 서비스 및 관련 정보를 제공하기 위해 운영하는 인터넷 웹사이트를 말합니다.\n"이용자"란 본 사이트에 접속하여 약관에 따라 학원이 제공하는 서비스를 이용하는 자를 말합니다.'),
  ('제3조 (약관의 효력 및 변경)', '본 약관은 사이트에 공시함으로써 효력이 발생합니다. 학원은 관련 법령에 위배되지 않는 범위 내에서 약관을 변경할 수 있으며, 변경된 약관은 사이트에 공시한 날로부터 효력이 발생합니다.'),
  ('제4조 (서비스의 제공)', E'학원은 다음과 같은 서비스를 제공합니다.\n- 교육과정 및 강사 소개 정보 제공\n- 입학 테스트 안내\n- 공지사항 및 학원 소식 제공'),
  ('제5조 (면책사항)', '학원은 천재지변, 불가항력, 또는 이에 준하는 사유로 서비스를 제공할 수 없는 경우에는 서비스 제공에 관한 책임이 면제됩니다.');

-- 개인정보처리방침
insert into privacy (title, content) values
  ('1. 개인정보의 수집 및 이용 목적', E'안보라은 다음 목적을 위해 개인정보를 수집·이용합니다. 수집한 개인정보는 아래 목적 이외의 용도로 이용되지 않으며, 목적이 변경될 경우 사전에 동의를 구합니다.\n- 수강 상담 및 입학 테스트 예약\n- 교육 서비스 제공 및 학습 관리\n- 공지사항 전달'),
  ('2. 수집하는 개인정보 항목', '성명, 연락처(전화번호), 학년, 학교명'),
  ('3. 개인정보의 보유 및 이용 기간', '수집된 개인정보는 수집 목적이 달성된 후 지체 없이 파기합니다. 단, 관계 법령에 의해 보존할 필요가 있는 경우 해당 법령에서 정한 기간 동안 보존합니다.'),
  ('4. 개인정보의 파기 절차 및 방법', '보유 기간이 경과하거나 처리 목적이 달성된 개인정보는 재생이 불가능한 방법으로 파기합니다.'),
  ('5. 개인정보 보호 책임자', E'성명: 안보라\n직위: 원장\n연락처: 02-556-8383\n이메일: privacy@anboraedu.co.kr'),
  ('6. 정책 변경', '본 개인정보처리방침은 2026년 1월 1일부터 시행됩니다. 변경 사항이 있을 경우 사이트를 통해 공지합니다.');


-- ============ 3단계: RLS (Row Level Security) 설정 ============
-- 읽기: 누구나 가능 (홍보 사이트)
-- 쓰기/수정/삭제: 인증된 관리자만 가능

DO $$
DECLARE
  tbl text;
BEGIN
  FOR tbl IN SELECT unnest(ARRAY[
    'banners','instructors','curriculum','notices','test_steps',
    'test_info','contacts','map_branches','map_info','terms','privacy'
  ])
  LOOP
    -- RLS 활성화
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', tbl);
    -- 누구나 읽기 가능
    EXECUTE format('CREATE POLICY "공개 읽기" ON %I FOR SELECT USING (true)', tbl);
    -- 인증된 사용자만 추가/수정/삭제 가능
    EXECUTE format('CREATE POLICY "관리자 추가" ON %I FOR INSERT WITH CHECK (auth.role() = ''authenticated'')', tbl);
    EXECUTE format('CREATE POLICY "관리자 수정" ON %I FOR UPDATE USING (auth.role() = ''authenticated'')', tbl);
    EXECUTE format('CREATE POLICY "관리자 삭제" ON %I FOR DELETE USING (auth.role() = ''authenticated'')', tbl);
  END LOOP;
END $$;
